# This is the default configuration of the theme, which can be overridden by custom configuration. For specific rules, please refer to: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes

[params]
