baseURL = '/' 
defaultContentLanguage = "en" #默认内容语言
defaultContentLanguageInSubdir = false #子目录显示默认内容

theme = "hugo-theme-misipage" #主题名称
themesdir = "../../" #主题路径

[languages.en]
contentDir = 'content/en'
hasCJKLanguage = false
languageCode = 'en'
languageName = 'English'
title = 'My New Hugo Site'
weight = 10

[languages.zh-Hans]
contentDir = 'content/zh-Hans'
hasCJKLanguage = true
languageCode = 'zh-Hans'
languageName = '简体中文'
title = 'My New Hugo Site'
weight = 20
